# Generated by Django 3.1.6 on 2021-03-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='listName',
            field=models.CharField(default='no name', max_length=200),
        ),
    ]
